### ISSUE TITLE
Testing lab

### ISSUE THREAD

**Issue by giraugh** [GRA0007/automatarium#56]
Create UI for Testing Lab component
- Will be rendered as a child of `SidePane`
- Styling not super important - focus on structure, state and rendering
- Can use the `useProjectStore` hook to get the current project. That project contains the states, transitions etc needed for simulation. This store would also need to contain the batch test inputs (check the architecture notion page for this)
- Use state in the component to store result of tests

<img width="192" alt="image" src="https://user-images.githubusercontent.com/16392483/159206721-b711f0fe-74fe-4ae0-af9f-6890fa67ae41.png">

**Comment by Prydeton** [comment]
Frontend for Testing Lab has been mostly completed with minor touch ups required
